### PR TITLE
Add display and undisplay commands to singlestep runner

### PR DESCRIPTION
**Pull request by klanmiko**
Use case: While stepping through programs on the dinocpu, it is helpful to know the instruction at pc. Usually a user would call `print inst`. However, this would have to be called after every step. GDB and most debuggers have a display function that stores a list of expressions to print after every step.

The goal of this PR is to add display functionality to the single-stepper.
`doDisplay` is run after each successful step, and there is a `displayList: ArrayBuffer[Array[String]]` in main that stores all the commands to display, directly from input. `displayCommandOkay` is used as an input validation guard in the command pattern matching part of main.

### CODE REVIEW

**Comment by powerjg** [comment]
This is awesome! Could you please update the single-stepper documentation with how to use this new feature?

**Comment by powerjg** [comment]
This is awesome! Could you please update the single-stepper documentation with how to use this new feature?

**Review by powerjg — COMMENTED** [review]
This is awesome! Could you please update the single-stepper documentation with how to use this new feature?

Also, does this merge cleanly with Kevin's update?

**Comment by klanmiko** [comment]
I've updated the documentation and merged in Kevin's changes

**Review by powerjg — APPROVED** [review]
Awesome! Thanks!

**Comment by powerjg** [comment]
Can you rebase this on top of master? I prefer rebases to merges :).

I tried doing it myself, but when I did the 'display" command didn't work.

See https://github.com/jlpteaching/dinocpu/tree/klanmiko-singlestep-enhance for what I tried :)

**Comment by klanmiko** [comment]
I've hammered away the merge commit with a rebase.

It looked like your rebase should have worked. The display command returns silently if there was no error, and will print the value on the next step. Idk if this should be mentioned in the documentation?

**Review by powerjg — COMMENTED** [review]
Looks pretty good to me. There's one thing that's not working, though. When I do `display reg 10` or `d reg 10` it just dumps the "help" each time.

Other than that, this is good to go!

**Comment by powerjg** [comment]
Thanks!

**Pull request merged**
