### PR TITLE
Potential solution for printing single stepper values

### PR DESCRIPTION
**Pull request by DanG100**
This is one way to implement a single stepper with more features, using the treadle repl. Adds printing and writing reg values (with tab completion).

Example usage
```
runMain dinocpu.replrunner add1 pipelined
> peek cpu.if_id_instruction
> step 5
```

### CODE REVIEW

**Review by powerjg — APPROVED** [review]
Cool! Should this replace the single stepper? It looks like it's a superset of the features. 

No need to address in this patch (maybe we should open a new issue), but can we list all of the possible things to print?

**Comment by DanG100** [comment]
The treadle repl has a function to list all the symbols, `symbol regex` This could replace single stepper. But if we want to add more features, we would have to fork treadle.

**Comment by powerjg** [comment]
What other features might we want to add?

**Comment by DanG100** [comment]
I didn't have anything in mind, but its just a consideration for future improvements

**Review by powerjg — APPROVED** [review]
Awesome!

**Comment by powerjg** [comment]
This is ready to merge, IMO.

The only thing missing is documentation. This can either be done in this PR before merging or in another PR. It's up to you.

**Pull request merged**
